/**
 * CMS type definitions for code generation and authoring.
 * Generated by Talizen CMS system, do't modify this file manually.
 * 
 * @see https://www.talizen.com/docs/cms
 */

export declare const CmsList: readonly [
]